controller:
  ingressClassResource:
    default: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
  config:
    proxy-body-size: 2g
