controller:
  ingressClassResource:
    default: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
  config:
    proxy-body-size: 2g
  extraArgs:
    default-ssl-certificate: "cert-manager/cluster-kuin-sh-tls"

tcp:
  22: gitea/gitea-ssh:22
