repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    createNamespace: true
    set:
      - name: configInline
        value: |
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 10.10.50.0-10.10.50.255

  - name: longhorn
    chart: longhorn/longhorn
    namespace: longhorn-system
    createNamespace: true

  - name: traefik
    chart: traefik/traefik
    namespace: ingress-traefik
    createNamespace: true

  - name: argo-cd
    chart: argo/argo-cd
    namespace: argo
    createNamespace: true
