helmDefaults:
  createNamespace: true
  cleanupOnFail: true
  wait: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io
  - name: rancher
    url: https://releases.rancher.com/server-charts/latest
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    values:
      - metallb/values.yml

  - name: longhorn
    chart: longhorn/longhorn
    namespace: longhorn-system

  - name: grafana
    chart: grafana/grafana
    namespace: grafana

  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: prometheus

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    values:
      - cert-manager/values.yml

  - name: external-dns
    chart: bitnami/external-dns
    namespace: external-dns

  - name: traefik
    chart: traefik/traefik
    namespace: ingress-traefik

  - name: argo-cd
    chart: argo/argo-cd
    namespace: argo
