apiVersion: k0sctl.k0sproject.io/v1
kind: Cluster
metadata:
  name: k0s-cluster

spec:
  hosts:
    - ssh:
        address: 10.0.0.1
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: controller
    - ssh:
        address: 10.0.0.1
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: controller
    - ssh:
        address: 10.0.0.1
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: controller

    - ssh:
        address: 10.0.0.2
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.0.0.2
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.0.0.2
        user: root
        port: 22
        keyPath: ~/.ssh/home_id_rsa
      role: worker
