apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster

spec:
  hosts:
    - ssh:
        address: 10.10.0.31
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: controller
    - ssh:
        address: 10.10.0.32
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: controller
    - ssh:
        address: 10.10.0.33
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: controller
    - ssh:
        address: 10.10.0.41
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.10.0.42
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.10.0.43
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.10.0.44
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: worker
    - ssh:
        address: 10.10.0.45
        user: shikun
        keyPath: ~/.ssh/home_id_rsa
      role: worker

  k0s:
    version: "v1.22.4+k0s.1"
    config:
      spec:
        telemetry:
          enabled: false
        api:
          externalAddress: 10.10.0.30
          sans:
            - 10.10.0.30
