- name: cluster
  hosts: cluster
  tasks:
    - name: full update using apt
      become: yes
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: "full"

    - name: install packages
      become: yes
      ansible.builtin.package:
        name:
          - nfs-common
          - qemu-guest-agent
        state: latest
