apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard-ingress
  namespace: tekton-pipelines

spec:
  rules:
    - host: tekton.cluster.kuin.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tekton-dashboard
                port:
                  number: 9097

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---
apiVersion: v1
kind: Service
metadata:
  name: keel-service
  namespace: kube-system

spec:
  selector:
    app: keel
  ports:
    - protocol: TCP
      port: 9300

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-webhook-ingress
  namespace: tekton-builds

spec:
  rules:
    - host: tekton-webhook.cluster.kuin.sh
      http:
        paths:
          - path: /api/webhook/website
            pathType: Prefix
            backend:
              service:
                name: el-webhook-website
                port:
                  number: 8080

          - path: /api/webhook/littlelink
            pathType: Prefix
            backend:
              service:
                name: el-webhook-littlelink
                port:
                  number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keel-ingress
  namespace: kube-system

spec:
  rules:
    - host: keel.cluster.kuin.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keel-service
                port:
                  number: 9300
