apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: gitlab

spec:
  isCA: true
  commonName: gitlab-selfsigned-ca
  secretName: selfsigned-ca
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
